### PR TITLE
Transaction support, placeholder slug for validation, and DX changes

### PR DESCRIPTION
**Pull request by thebigredgeek**
added transaction support, placeholder slug for validation, and updated tests for easier portability

### CODE REVIEW

**Comment by thebigredgeek** [comment]
https://github.com/jarrodconnolly/sequelize-slugify/issues/9

**Comment by thebigredgeek** [comment]
Not sure what to do about tests here.  It looks like it might be difficult to test :(

**Comment by thebigredgeek** [comment]
@jarrodconnolly

**Comment by davericher** [comment]
bump

**Comment by jarrodconnolly** [comment]
Thank you for this contribution, it led me to better understand how Sequelize passes transactions to hooks. This has been implemented in an upcoming release of 1.x of this project.

**Pull request closed without merging**
